import type { Drug, Pharmacy, PharmacyBranch, DrugPrice, StockStatus, DataSource } from "./types"

// Farmacias base
export const mockPharmacies: Pharmacy[] = [
    { id: "pharm-1", name: "InkaFarma", logo: "/inkafarma-logo.jpg" },
    { id: "pharm-2", name: "MiFarma", logo: "/mifarma-logo.jpg" },
    { id: "pharm-3", name: "Boticas Arcángel", logo: "/boticas-arcangel-logo.jpg" },
    { id: "pharm-4", name: "Farmacia Universal", logo: "/farmacia-universal-logo.jpg" },
    { id: "pharm-5", name: "Boticas y Salud", logo: "/boticas-y-salud-logo.jpg" },
]

// Sucursales de farmacias en Lima Metropolitana (dentro de 5km desde centro de Lima)
export const mockBranches: PharmacyBranch[] = [
    {
        id: "branch-1",
        pharmacyId: "pharm-1",
        pharmacyName: "InkaFarma",
        address: "Av. Javier Prado Este 1234",
        district: "San Isidro",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.0954, lng: -77.0397 },
        phone: "+51 1 234-5678",
        hours: "24 horas",
        isOpen24Hours: true,
        rating: 4.5,
    },
    {
        id: "branch-2",
        pharmacyId: "pharm-2",
        pharmacyName: "MiFarma",
        address: "Av. Larco 789",
        district: "Miraflores",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.1215, lng: -77.0298 },
        phone: "+51 1 234-5679",
        hours: "7:00 AM - 11:00 PM",
        isOpen24Hours: false,
        rating: 4.3,
    },
    {
        id: "branch-3",
        pharmacyId: "pharm-3",
        pharmacyName: "Boticas Arcángel",
        address: "Av. El Ejército 456",
        district: "Miraflores",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.1198, lng: -77.028 },
        phone: "+51 1 234-5680",
        hours: "8:00 AM - 10:00 PM",
        isOpen24Hours: false,
        rating: 4.2,
    },
    {
        id: "branch-4",
        pharmacyId: "pharm-4",
        pharmacyName: "Farmacia Universal",
        address: "Jirón de la Unión 567",
        district: "Lima Centro",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.0464, lng: -77.0306 },
        phone: "+51 1 234-5681",
        hours: "6:00 AM - 12:00 AM",
        isOpen24Hours: false,
        rating: 4.0,
    },
    {
        id: "branch-5",
        pharmacyId: "pharm-5",
        pharmacyName: "Boticas y Salud",
        address: "Av. Brasil 890",
        district: "Breña",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.0598, lng: -77.0522 },
        phone: "+51 1 234-5682",
        hours: "7:00 AM - 11:00 PM",
        isOpen24Hours: false,
        rating: 4.1,
    },
    {
        id: "branch-6",
        pharmacyId: "pharm-1",
        pharmacyName: "InkaFarma",
        address: "Av. Arequipa 2100",
        district: "Lince",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.0823, lng: -77.0375 },
        phone: "+51 1 234-5683",
        hours: "24 horas",
        isOpen24Hours: true,
        rating: 4.4,
    },
    {
        id: "branch-7",
        pharmacyId: "pharm-2",
        pharmacyName: "MiFarma",
        address: "Av. Alfredo Benavides 3456",
        district: "Santiago de Surco",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.1342, lng: -77.0012 },
        phone: "+51 1 234-5684",
        hours: "7:00 AM - 11:00 PM",
        isOpen24Hours: false,
        rating: 4.5,
    },
    {
        id: "branch-8",
        pharmacyId: "pharm-3",
        pharmacyName: "Boticas Arcángel",
        address: "Av. La Marina 2567",
        district: "San Miguel",
        city: "Lima",
        region: "Lima",
        coordinates: { lat: -12.0761, lng: -77.0872 },
        phone: "+51 1 234-5685",
        hours: "8:00 AM - 10:00 PM",
        isOpen24Hours: false,
        rating: 4.3,
    },
]

// Catálogo de medicamentos normalizados (Drug Catalog)
export const mockDrugs: Drug[] = [
    {
        id: "drug-1",
        dci: "Paracetamol",
        commercialNames: ["Paracetamol Genérico", "Tylenol", "Panadol"],
        pharmaceuticalForm: "Tableta",
        concentration: "500mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Paracetamol",
        presentation: "Caja x 20 tabletas",
        requiresPrescription: false,
        isActive: true,
        indications: [
            "Alivio temporal de dolores leves a moderados",
            "Reducción de la fiebre",
            "Dolor de cabeza y migraña",
        ],
        contraindications: ["Hipersensibilidad al paracetamol", "Insuficiencia hepática grave"],
        dosage: "Adultos: 1-2 tabletas cada 4-6 horas. Máximo 8 tabletas en 24 horas.",
        warnings: ["No exceder la dosis recomendada", "Consultar médico si síntomas persisten por más de 3 días"],
        storageConditions: "Conservar en lugar seco y fresco, temperatura no mayor a 30°C.",
    },
    {
        id: "drug-2",
        dci: "Ibuprofeno",
        commercialNames: ["Ibuprofeno Genérico", "Advil", "Motrin"],
        pharmaceuticalForm: "Tableta",
        concentration: "400mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Ibuprofeno",
        presentation: "Caja x 20 tabletas",
        requiresPrescription: false,
        isActive: true,
        indications: ["Dolor e inflamación leve a moderada", "Fiebre", "Artritis reumatoide", "Dolor dental"],
        contraindications: ["Úlcera péptica activa", "Insuficiencia renal grave", "Embarazo (tercer trimestre)"],
        dosage: "Adultos: 1 tableta cada 6-8 horas. Máximo 1200mg diarios.",
        warnings: [
            "Tomar con alimentos para reducir molestias gástricas",
            "No administrar en niños menores de 12 años sin supervisión médica",
        ],
        storageConditions: "Conservar a temperatura ambiente, protegido de la humedad.",
    },
    {
        id: "drug-3",
        dci: "Amoxicilina",
        commercialNames: ["Amoxicilina Genérica", "Amoxil", "Trimox"],
        pharmaceuticalForm: "Cápsula",
        concentration: "500mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Amoxicilina",
        presentation: "Caja x 21 cápsulas",
        requiresPrescription: true,
        isActive: true,
        indications: [
            "Infecciones bacterianas del tracto respiratorio",
            "Infecciones urinarias",
            "Infecciones de piel y tejidos blandos",
        ],
        contraindications: ["Alergia a penicilinas", "Mononucleosis infecciosa"],
        dosage: "Adultos: 500mg cada 8 horas por 7-10 días según prescripción médica.",
        warnings: [
            "Completar el tratamiento según indicación médica",
            "Informar al médico si aparecen erupciones cutáneas",
        ],
        storageConditions: "Conservar en lugar fresco y seco.",
    },
    {
        id: "drug-4",
        dci: "Omeprazol",
        commercialNames: ["Omeprazol Genérico", "Losec", "Prilosec"],
        pharmaceuticalForm: "Cápsula",
        concentration: "20mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Omeprazol",
        presentation: "Caja x 14 cápsulas",
        requiresPrescription: false,
        isActive: true,
        indications: ["Úlcera gástrica y duodenal", "Reflujo gastroesofágico", "Hiperacidez estomacal"],
        contraindications: ["Hipersensibilidad al omeprazol", "Uso concomitante con atazanavir"],
        dosage: "Adultos: 1 cápsula al día en ayunas por 2-4 semanas.",
        warnings: ["Tomar en ayunas 30-60 minutos antes del desayuno", "Consultar médico si síntomas persisten"],
        storageConditions: "Conservar en lugar seco, protegido de la luz.",
    },
    {
        id: "drug-5",
        dci: "Loratadina",
        commercialNames: ["Loratadina Genérica", "Claritin", "Alavert"],
        pharmaceuticalForm: "Tableta",
        concentration: "10mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Loratadina",
        presentation: "Caja x 10 tabletas",
        requiresPrescription: false,
        isActive: true,
        indications: ["Alivio de síntomas de rinitis alérgica", "Urticaria", "Picazón y estornudos"],
        contraindications: ["Hipersensibilidad a loratadina", "Niños menores de 2 años"],
        dosage: "Adultos: 1 tableta al día.",
        warnings: ["No causa somnolencia en la mayoría de personas", "Evitar alcohol durante el tratamiento"],
        storageConditions: "Conservar a temperatura ambiente.",
    },
    {
        id: "drug-6",
        dci: "Diclofenaco",
        commercialNames: ["Diclofenaco Genérico", "Voltaren", "Cataflam"],
        pharmaceuticalForm: "Tableta",
        concentration: "50mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Diclofenaco sódico",
        presentation: "Caja x 20 tabletas",
        requiresPrescription: false,
        isActive: true,
        indications: ["Dolor e inflamación musculoesquelética", "Artritis", "Dolor postoperatorio"],
        contraindications: ["Úlcera péptica activa", "Insuficiencia cardíaca severa", "Embarazo (tercer trimestre)"],
        dosage: "Adultos: 1 tableta 2-3 veces al día con alimentos.",
        warnings: ["Puede aumentar el riesgo cardiovascular", "Monitorear función renal en tratamientos prolongados"],
        storageConditions: "Conservar en lugar fresco y seco, protegido de la luz.",
    },
    {
        id: "drug-7",
        dci: "Metformina",
        commercialNames: ["Metformina Genérica", "Glucophage"],
        pharmaceuticalForm: "Tableta",
        concentration: "850mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Metformina clorhidrato",
        presentation: "Caja x 30 tabletas",
        requiresPrescription: true,
        isActive: true,
        indications: ["Diabetes mellitus tipo 2", "Síndrome de ovario poliquístico (en algunos casos)"],
        contraindications: ["Insuficiencia renal", "Acidosis metabólica", "Insuficiencia cardíaca descompensada"],
        dosage: "Adultos: Según prescripción médica, generalmente 1 tableta 2-3 veces al día con alimentos.",
        warnings: [
            "Control médico regular de función renal",
            "Suspender antes de procedimientos con contraste radiológico",
        ],
        storageConditions: "Conservar a temperatura ambiente, protegido de la humedad.",
    },
    {
        id: "drug-8",
        dci: "Atorvastatina",
        commercialNames: ["Atorvastatina Genérica", "Lipitor"],
        pharmaceuticalForm: "Tableta",
        concentration: "20mg",
        isGeneric: true,
        laboratory: "Varios",
        activeIngredient: "Atorvastatina cálcica",
        presentation: "Caja x 30 tabletas",
        requiresPrescription: true,
        isActive: true,
        indications: ["Hipercolesterolemia", "Prevención de enfermedades cardiovasculares", "Dislipidemia"],
        contraindications: ["Enfermedad hepática activa", "Embarazo y lactancia", "Hipersensibilidad al fármaco"],
        dosage: "Adultos: 1 tableta al día, preferiblemente en la noche.",
        warnings: ["Control periódico de función hepática", "Reportar dolor muscular inexplicado"],
        storageConditions: "Conservar a temperatura ambiente.",
    },
]

// Precios por sucursal (DrugPrice)
// Función helper para generar múltiples precios
const generatePrices = (): DrugPrice[] => {
    const prices: DrugPrice[] = []
    const sources: DataSource[] = ["SNIP", "PHARMACY_API", "MANUAL"]
    const stockStatuses: StockStatus[] = ["IN_STOCK", "LOW", "OUT_OF_STOCK"]

    // Precios para Paracetamol (drug-1) - Genérico y Marca
    prices.push(
        {
            id: "price-1",
            drugId: "drug-1",
            branchId: "branch-1",
            price: 8.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 25,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-2",
            drugId: "drug-1",
            branchId: "branch-2",
            price: 9.2,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 18,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-3",
            drugId: "drug-1",
            branchId: "branch-3",
            price: 7.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 30,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-4",
            drugId: "drug-1",
            branchId: "branch-4",
            price: 10.5,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 5,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-13"),
        },
        {
            id: "price-5",
            drugId: "drug-1",
            branchId: "branch-6",
            price: 8.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 20,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-15"),
        },
    )

    // Precios para Ibuprofeno (drug-2)
    prices.push(
        {
            id: "price-6",
            drugId: "drug-2",
            branchId: "branch-1",
            price: 12.3,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 15,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-7",
            drugId: "drug-2",
            branchId: "branch-2",
            price: 13.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 12,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-8",
            drugId: "drug-2",
            branchId: "branch-3",
            price: 11.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 20,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-9",
            drugId: "drug-2",
            branchId: "branch-5",
            price: 14.2,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 3,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-12"),
        },
        {
            id: "price-10",
            drugId: "drug-2",
            branchId: "branch-7",
            price: 12.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 18,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-15"),
        },
    )

    // Precios para Amoxicilina (drug-3)
    prices.push(
        {
            id: "price-11",
            drugId: "drug-3",
            branchId: "branch-1",
            price: 25.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 10,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-12",
            drugId: "drug-3",
            branchId: "branch-2",
            price: 27.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 8,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-13",
            drugId: "drug-3",
            branchId: "branch-4",
            price: 24.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 15,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-14",
            drugId: "drug-3",
            branchId: "branch-6",
            price: 26.2,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 4,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-13"),
        },
    )

    // Precios para Omeprazol (drug-4)
    prices.push(
        {
            id: "price-15",
            drugId: "drug-4",
            branchId: "branch-1",
            price: 18.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 22,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-16",
            drugId: "drug-4",
            branchId: "branch-2",
            price: 19.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 16,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-17",
            drugId: "drug-4",
            branchId: "branch-3",
            price: 17.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 25,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-18",
            drugId: "drug-4",
            branchId: "branch-5",
            price: 20.1,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 12,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-13"),
        },
        {
            id: "price-19",
            drugId: "drug-4",
            branchId: "branch-8",
            price: 18.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 18,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-15"),
        },
    )

    // Precios para Loratadina (drug-5)
    prices.push(
        {
            id: "price-20",
            drugId: "drug-5",
            branchId: "branch-1",
            price: 14.2,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 30,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-21",
            drugId: "drug-5",
            branchId: "branch-2",
            price: 15.0,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 24,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-22",
            drugId: "drug-5",
            branchId: "branch-4",
            price: 13.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 20,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-23",
            drugId: "drug-5",
            branchId: "branch-7",
            price: 14.5,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 6,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-12"),
        },
    )

    // Precios para Diclofenaco (drug-6)
    prices.push(
        {
            id: "price-24",
            drugId: "drug-6",
            branchId: "branch-1",
            price: 16.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 20,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-25",
            drugId: "drug-6",
            branchId: "branch-3",
            price: 17.2,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 14,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-26",
            drugId: "drug-6",
            branchId: "branch-5",
            price: 15.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 18,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-27",
            drugId: "drug-6",
            branchId: "branch-8",
            price: 16.8,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 5,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-13"),
        },
    )

    // Precios para Metformina (drug-7)
    prices.push(
        {
            id: "price-28",
            drugId: "drug-7",
            branchId: "branch-1",
            price: 22.5,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 12,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-29",
            drugId: "drug-7",
            branchId: "branch-2",
            price: 24.0,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 10,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-30",
            drugId: "drug-7",
            branchId: "branch-4",
            price: 21.8,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 15,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-31",
            drugId: "drug-7",
            branchId: "branch-6",
            price: 23.2,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 4,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-13"),
        },
    )

    // Precios para Atorvastatina (drug-8)
    prices.push(
        {
            id: "price-32",
            drugId: "drug-8",
            branchId: "branch-1",
            price: 35.6,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 8,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-33",
            drugId: "drug-8",
            branchId: "branch-2",
            price: 37.2,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 6,
            source: "PHARMACY_API",
            lastUpdated: new Date("2024-01-14"),
        },
        {
            id: "price-34",
            drugId: "drug-8",
            branchId: "branch-3",
            price: 34.9,
            currency: "PEN",
            stockStatus: "IN_STOCK",
            stockQuantity: 10,
            source: "SNIP",
            lastUpdated: new Date("2024-01-15"),
        },
        {
            id: "price-35",
            drugId: "drug-8",
            branchId: "branch-7",
            price: 36.5,
            currency: "PEN",
            stockStatus: "LOW",
            stockQuantity: 3,
            source: "MANUAL",
            lastUpdated: new Date("2024-01-12"),
        },
    )

    return prices
}

export const mockPrices: DrugPrice[] = generatePrices()

// Función para obtener branch por ID
export function getBranchById(branchId: string): PharmacyBranch | undefined {
    return mockBranches.find((b) => b.id === branchId)
}

// Función para obtener drug por ID
export function getDrugById(drugId: string): Drug | undefined {
    return mockDrugs.find((d) => d.id === drugId)
}

// Función para obtener precios de un medicamento
export function getPricesForDrug(drugId: string): DrugPrice[] {
    return mockPrices.filter((p) => p.drugId === drugId)
}
